# Generated by Django 3.1.5 on 2021-01-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominiofeliz', '0003_auto_20210121_0630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
